# Generated by Django 4.1 on 2022-08-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Slots", "0005_slot_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["start_time", "end_time"]},
        ),
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["date", "schedule"]},
        ),
    ]
