# Generated by Django 4.1 on 2022-08-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Slots", "0006_alter_schedule_options_alter_slot_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["day", "start_time", "end_time"]},
        ),
    ]
